name: Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get changes files
        id: changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main -- '*.py')
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Run isort on changes files
        if: steps.changes.outputs.files != ''
        run: |
          echo "$CHANGED_FILES" | xargs -r isort --check --diff

      - name: Run black on changes files
        if: steps.changes.outputs.files != ''
        run: |
          echo "$CHANGED_FILES" | xargs -r black --check --diff

      - name: Run flake8 on changes files
        if: steps.changes.outputs.files != ''
        run: |
          echo "$CHANGED_FILES" | xargs -r flake8
